using UnityEngine;
using UnityEngine.Events;
namespace Humber.GAME205
{
    public abstract class Shape : MonoBehaviour
    {
        // Events
        [Header("Events")]
        [Tooltip("Whenever the data of this shape is changed, this event will be invoked.")]
        public UnityEvent ValuesChanged;

        // Inspector/Public Fields
        [SerializeField] // This field will be visible in the inspector even though it is private to access in code.
        [HideInInspector] 
        private int handle = 0;
        
        /// <summary>
        /// The handle is generated by the Physics Native API and can only be set once by the library.
        /// </summary>
        public int Handle
        {
            get { return handle; }
            set
            {
                //preventing it to be changed only once
                if (handle == 0)
                {
                    if (value < 0)
                    {
                        handle = 0;
                    }
                    else
                    {
                        handle = value;
                    }
                }
            }
        }

        protected abstract void OnValidate();
    }
}